version: '3.4'

services:
  postgres:
    container_name: postgresql-deadlocks
    image: "postgres:14.12"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
